import { formatFixed, displayDecimalsFor, type ExactAmount } from './decimal';
import type { AccountCoverage, ProviderCoverage } from './coverage';

/**
 * Report artifacts, all derived from one canonical dataset.
 *
 * The dataset is what the report IS; CSV, HTML and PDF are views of it. No
 * renderer computes a total — every figure it prints was summed exactly
 * upstream (in Postgres and re-checked in `decimal.ts`) and arrives here as
 * a decimal string. A renderer that disagreed with the JSON would be a bug
 * in the renderer, never a second opinion.
 *
 * This module has no server-only import so the text formats can be tested
 * as pure functions; the PDF renderer loads jsPDF lazily.
 */

export const RENDERER_VERSION = 'finance-report-renderer/1.0.0';
export const DATASET_SCHEMA = 'coinpay.finance-report/1';

export const GENERATED_BY_NOTICE =
  'Generated by CoinPay from imported account data; not an institution-issued statement.';

export interface ReportRow {
  id: string;
  accountId: string;
  externalId: string;
  posted: string | null;
  transactedAt: string | null;
  amount: ExactAmount;
  description: string | null;
  payee: string | null;
  memo: string | null;
  mcc: string | null;
  category: string | null;
  revision: number;
}

export interface ReportAccount {
  id: string;
  name: string;
  orgName: string | null;
  currency: string;
  kind: string;
  scope: string;
  isHidden: boolean;
  identityState: string;
  /** The balance the provider last reported, and when. Not a period balance. */
  currentBalance: ExactAmount | null;
  currentBalanceAsOf: string | null;
  availableBalance: ExactAmount | null;
  /** Period boundaries are unknown unless a statement supplies them. */
  openingBalance: ExactAmount | null;
  closingBalance: ExactAmount | null;
  balanceProvenance: 'unavailable' | 'user_statement_entry' | 'provider_snapshot';
}

export interface CurrencyTotals {
  currency: string;
  credits: ExactAmount;
  debits: ExactAmount;
  net: ExactAmount;
  rows: number;
}

export interface AccountTotals {
  accountId: string;
  credits: ExactAmount;
  debits: ExactAmount;
  net: ExactAmount;
  rows: number;
}

export interface ReportDataset {
  schema: typeof DATASET_SCHEMA;
  report: {
    id: string;
    revision: number;
    merchantId: string;
    periodKind: string;
    periodSelector: string;
    periodLabel: string;
    timezone: string;
    requestedStart: string;
    requestedEnd: string;
    effectiveEnd: string;
    periodToDate: boolean;
    cutoff: string;
    scope: string;
    includeHidden: boolean;
    includePending: boolean;
    generatedAt: string;
    snapshotAt: string;
    rendererVersion: string;
  };
  accounts: ReportAccount[];
  posted: ReportRow[];
  pending: ReportRow[];
  totals: CurrencyTotals[];
  accountTotals: AccountTotals[];
  coverage: {
    local_export_complete: boolean;
    provider_coverage: ProviderCoverage;
    reconciliation_status: string;
    accounts: AccountCoverage[];
    warnings: string[];
    explanation: string;
  };
  statements: Array<{ id: string; accountId: string; institutionLabel: string | null; periodStart: string; periodEnd: string }>;
  disclaimers: string[];
}

/** Stable JSON: keys sorted, no whitespace. The hash is over this. */
export function canonicalJson(value: unknown): string {
  return JSON.stringify(sortKeys(value));
}

function sortKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort()) {
      out[key] = sortKeys((value as Record<string, unknown>)[key]);
    }
    return out;
  }
  return value;
}

export function coverageExplanation(coverage: ProviderCoverage, periodToDate: boolean): string {
  const base =
    coverage === 'available_window_fetched'
      ? 'Every part of this period was fetched from the provider at least once. That is what the provider made available; it is not independent verification that the institution supplied complete history.'
      : coverage === 'partial'
        ? 'Part of this period was never fetched from the provider, or a fetch was cut short. History may be incomplete.'
        : 'No part of this period is known to have been fetched from the provider. The rows below are whatever was already imported; history may be incomplete.';
  return periodToDate ? `${base} The period is still running (period to date).` : base;
}

// ---------------------------------------------------------------------------
// CSV
// ---------------------------------------------------------------------------

const CSV_COLUMNS = [
  'section',
  'account_name',
  'institution',
  'currency',
  'posted',
  'transacted_at',
  'amount',
  'description',
  'payee',
  'memo',
  'category',
  'mcc',
  'pending',
  'external_id',
  'account_id',
  'transaction_id',
] as const;

/**
 * Quote a text field for CSV and neutralise spreadsheet formula prefixes.
 *
 * A description beginning with `=`, `+`, `-`, `@`, or a tab/CR is executed
 * as a formula by Excel and LibreOffice when the file is opened. Prefixing a
 * single quote makes it text. Amounts are emitted by `csvNumber`, which is
 * why a negative amount is unaffected.
 */
export function csvText(value: string | null | undefined): string {
  if (value === null || value === undefined) return '';
  let text = String(value);
  if (/^[=+\-@\t\r]/.test(text)) text = `'${text}`;
  if (/[",\r\n]/.test(text)) text = `"${text.replace(/"/g, '""')}"`;
  return text;
}

function csvNumber(value: ExactAmount | null): string {
  return value ?? '';
}

export function renderCsv(ds: ReportDataset): string {
  const accountById = new Map(ds.accounts.map((a) => [a.id, a]));
  const lines: string[] = [];
  lines.push(`# ${GENERATED_BY_NOTICE}`);
  lines.push(`# Report ${ds.report.id} revision ${ds.report.revision}; period ${ds.report.periodLabel} (${ds.report.timezone}); generated ${ds.report.generatedAt}`);
  lines.push(`# Provider coverage: ${ds.coverage.provider_coverage}; local export complete: ${ds.coverage.local_export_complete}; posted rows: ${ds.posted.length}; pending rows: ${ds.pending.length}`);
  lines.push(CSV_COLUMNS.join(','));

  const emit = (section: 'posted' | 'pending', row: ReportRow) => {
    const account = accountById.get(row.accountId);
    lines.push(
      [
        section,
        csvText(account?.name ?? ''),
        csvText(account?.orgName ?? ''),
        csvText(account?.currency ?? ''),
        csvText(row.posted),
        csvText(row.transactedAt),
        csvNumber(row.amount),
        csvText(row.description),
        csvText(row.payee),
        csvText(row.memo),
        csvText(row.category),
        csvText(row.mcc),
        section === 'pending' ? 'true' : 'false',
        csvText(row.externalId),
        csvText(row.accountId),
        csvText(row.id),
      ].join(','),
    );
  };
  for (const row of ds.posted) emit('posted', row);
  for (const row of ds.pending) emit('pending', row);
  return lines.join('\r\n') + '\r\n';
}

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

export function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function money(amount: ExactAmount | null, currency: string): string {
  if (amount === null) return '—';
  return formatFixed(amount, displayDecimalsFor(currency));
}

function dateOnly(iso: string | null, timeZone: string): string {
  if (!iso) return '';
  try {
    return new Intl.DateTimeFormat('en-CA', { timeZone, year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(iso));
  } catch {
    return iso.slice(0, 10);
  }
}

const HTML_CSS = `
:root{color-scheme:light}
body{font:13px/1.45 -apple-system,Segoe UI,Helvetica,Arial,sans-serif;color:#111;margin:0;padding:24px;background:#fff}
h1{font-size:20px;margin:0 0 4px}h2{font-size:15px;margin:24px 0 8px;border-bottom:1px solid #ddd;padding-bottom:4px}
.meta{color:#555;font-size:12px}.notice{border:1px solid #c9a227;background:#fff8dc;padding:8px 10px;margin:12px 0;font-size:12px}
.warn{border:1px solid #d33;background:#fff0f0;padding:8px 10px;margin:12px 0;font-size:12px}
table{border-collapse:collapse;width:100%;font-size:12px}th,td{border-bottom:1px solid #e5e5e5;padding:4px 6px;text-align:left;vertical-align:top}
th{background:#f5f5f5;font-weight:600}td.num,th.num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
thead{display:table-header-group}tr{page-break-inside:avoid}
.badge{display:inline-block;border:1px solid #999;border-radius:3px;padding:0 5px;font-size:11px;margin-right:4px}
@media print{body{padding:0}}
`;

export function renderHtml(ds: ReportDataset): string {
  const tz = ds.report.timezone;
  const accountById = new Map(ds.accounts.map((a) => [a.id, a]));
  const badges: string[] = [];
  if (ds.report.periodToDate) badges.push('Period to date');
  if (ds.coverage.provider_coverage !== 'available_window_fetched') badges.push('History may be incomplete');
  if (ds.accounts.some((a) => a.openingBalance === null)) badges.push('Opening balance unavailable');

  const totalsRows = ds.totals
    .map(
      (t) => `<tr><td>${escapeHtml(t.currency)}</td><td class="num">${escapeHtml(money(t.credits, t.currency))}</td><td class="num">${escapeHtml(money(t.debits, t.currency))}</td><td class="num">${escapeHtml(money(t.net, t.currency))}</td><td class="num">${t.rows}</td></tr>`,
    )
    .join('');

  const accountRows = ds.accounts
    .map((a) => {
      const t = ds.accountTotals.find((x) => x.accountId === a.id);
      const cov = ds.coverage.accounts.find((c) => c.accountId === a.id);
      return `<tr><td>${escapeHtml(a.name)}<br><span class="meta">${escapeHtml(a.orgName ?? '')} · ${escapeHtml(a.kind)} · ${escapeHtml(a.scope)}</span></td><td>${escapeHtml(a.currency)}</td><td class="num">${escapeHtml(a.openingBalance === null ? 'unavailable' : money(a.openingBalance, a.currency))}</td><td class="num">${t ? escapeHtml(money(t.credits, a.currency)) : '0'}</td><td class="num">${t ? escapeHtml(money(t.debits, a.currency)) : '0'}</td><td class="num">${t ? escapeHtml(money(t.net, a.currency)) : '0'}</td><td class="num">${escapeHtml(a.closingBalance === null ? 'unavailable' : money(a.closingBalance, a.currency))}</td><td class="num">${escapeHtml(a.currentBalance === null ? '—' : money(a.currentBalance, a.currency))}<br><span class="meta">as of ${escapeHtml(a.currentBalanceAsOf ?? 'unknown')}</span></td><td>${escapeHtml(cov?.coverage ?? 'unknown')}</td></tr>`;
    })
    .join('');

  const ledgerRows = (rows: ReportRow[]) =>
    rows
      .map((r) => {
        const a = accountById.get(r.accountId);
        const currency = a?.currency ?? '';
        return `<tr><td>${escapeHtml(dateOnly(r.posted ?? r.transactedAt, tz))}</td><td>${escapeHtml(a?.name ?? '')}</td><td>${escapeHtml(r.description ?? r.payee ?? '')}${r.payee && r.description ? `<br><span class="meta">${escapeHtml(r.payee)}</span>` : ''}</td><td>${escapeHtml(r.category ?? '')}</td><td>${escapeHtml(currency)}</td><td class="num">${escapeHtml(money(r.amount, currency))}</td></tr>`;
      })
      .join('');

  const warnings = ds.coverage.warnings.length
    ? `<div class="warn"><strong>Warnings</strong><ul>${ds.coverage.warnings.map((w) => `<li>${escapeHtml(w)}</li>`).join('')}</ul></div>`
    : '';

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'">
<title>${escapeHtml(ds.report.periodLabel)} activity report</title><style>${HTML_CSS}</style></head>
<body>
<h1>${escapeHtml(ds.report.periodKind === 'quarter' ? 'Quarterly' : ds.report.periodKind === 'month' ? 'Monthly' : 'Custom period')} activity report — ${escapeHtml(ds.report.periodLabel)}</h1>
<div class="meta">Period ${escapeHtml(ds.report.requestedStart)} to ${escapeHtml(ds.report.effectiveEnd)} (exclusive) in ${escapeHtml(tz)} · Scope ${escapeHtml(ds.report.scope)} · ${ds.accounts.length} account(s) · Report ${escapeHtml(ds.report.id)} rev ${ds.report.revision} · Generated ${escapeHtml(ds.report.generatedAt)}</div>
<div class="meta">${badges.map((b) => `<span class="badge">${escapeHtml(b)}</span>`).join('')}</div>
<div class="notice"><strong>${escapeHtml(GENERATED_BY_NOTICE)}</strong><br>${escapeHtml(ds.coverage.explanation)}<br>Local export complete: ${ds.coverage.local_export_complete ? 'yes' : 'NO'} · Provider coverage: ${escapeHtml(ds.coverage.provider_coverage)} · Reconciliation: ${escapeHtml(ds.coverage.reconciliation_status)}</div>
${warnings}
<h2>Gross bank flows by currency</h2>
<div class="meta">Credits are money into the account and debits money out. A credit is not automatically revenue and a debit is not automatically a deductible expense. Currencies are never combined.</div>
<table><thead><tr><th>Currency</th><th class="num">Credits</th><th class="num">Debits</th><th class="num">Net activity</th><th class="num">Posted rows</th></tr></thead><tbody>${totalsRows || '<tr><td colspan="5">No posted activity in this period.</td></tr>'}</tbody></table>
<h2>Accounts</h2>
<table><thead><tr><th>Account</th><th>Currency</th><th class="num">Opening</th><th class="num">Credits</th><th class="num">Debits</th><th class="num">Net</th><th class="num">Closing</th><th class="num">Current balance</th><th>Coverage</th></tr></thead><tbody>${accountRows}</tbody></table>
<div class="meta">Opening and closing balances are shown only when supplied from a statement. The current balance is the provider's latest figure with its own timestamp; it is not the closing balance of this period.</div>
<h2>Posted ledger (${ds.posted.length})</h2>
<table><thead><tr><th>Date</th><th>Account</th><th>Description</th><th>Category</th><th>Cur.</th><th class="num">Amount</th></tr></thead><tbody>${ledgerRows(ds.posted) || '<tr><td colspan="6">No posted transactions.</td></tr>'}</tbody></table>
${ds.report.includePending ? `<h2>Pending appendix (${ds.pending.length})</h2><div class="meta">Pending items are not included in any total above.</div><table><thead><tr><th>Date</th><th>Account</th><th>Description</th><th>Category</th><th>Cur.</th><th class="num">Amount</th></tr></thead><tbody>${ledgerRows(ds.pending) || '<tr><td colspan="6">No pending transactions.</td></tr>'}</tbody></table>` : ''}
${ds.statements.length ? `<h2>Linked statements</h2><ul>${ds.statements.map((s) => `<li>${escapeHtml(s.institutionLabel ?? 'Imported bank statement')} — ${escapeHtml(s.periodStart)} to ${escapeHtml(s.periodEnd)} (user supplied, not verified)</li>`).join('')}</ul>` : ''}
<h2>Notes</h2><ul>${ds.disclaimers.map((d) => `<li>${escapeHtml(d)}</li>`).join('')}</ul>
</body></html>`;
}

// ---------------------------------------------------------------------------
// PDF
// ---------------------------------------------------------------------------

/**
 * Rows the PDF ledger carries before it switches to a summary-plus-excerpt.
 * The CSV and JSON always hold every row; this bounds only the PDF, whose
 * per-row cost is a page layout. Configurable with FINANCES_PDF_MAX_ROWS.
 */
export function pdfMaxRows(): number {
  const n = Number(process.env.FINANCES_PDF_MAX_ROWS ?? 20_000);
  return Number.isFinite(n) && n > 0 ? n : 20_000;
}

export async function renderPdf(ds: ReportDataset): Promise<Buffer> {
  const { jsPDF } = await import('jspdf');
  const autoTable = (await import('jspdf-autotable')).default;
  const tz = ds.report.timezone;
  const accountById = new Map(ds.accounts.map((a) => [a.id, a]));

  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'letter', compress: true });
  // Deterministic metadata: two renders of one dataset should agree, so the
  // creation date comes from the dataset and the file id from the report
  // identity rather than jsPDF's random default.
  doc.setCreationDate(new Date(ds.report.generatedAt));
  const { createHash } = await import('crypto');
  doc.setFileId(createHash('md5').update(`${ds.report.id}:${ds.report.revision}:${ds.report.generatedAt}`).digest('hex').toUpperCase());
  doc.setProperties({
    title: `${ds.report.periodLabel} activity report`,
    subject: GENERATED_BY_NOTICE,
    creator: RENDERER_VERSION,
  });

  const margin = 40;
  let y = margin;
  doc.setFontSize(16);
  doc.text(`${ds.report.periodKind === 'quarter' ? 'Quarterly' : ds.report.periodKind === 'month' ? 'Monthly' : 'Custom period'} activity report: ${ds.report.periodLabel}`, margin, y);
  y += 18;
  doc.setFontSize(9);
  doc.setTextColor(80);
  const metaLines = [
    `Period ${ds.report.requestedStart} to ${ds.report.effectiveEnd} (exclusive), ${tz}. Scope ${ds.report.scope}. ${ds.accounts.length} account(s).`,
    `Report ${ds.report.id} revision ${ds.report.revision}. Generated ${ds.report.generatedAt}.`,
    ...(ds.report.periodToDate ? ['PERIOD TO DATE: the period is still running.'] : []),
    GENERATED_BY_NOTICE,
    ds.coverage.explanation,
    `Local export complete: ${ds.coverage.local_export_complete ? 'yes' : 'NO'}. Provider coverage: ${ds.coverage.provider_coverage}. Reconciliation: ${ds.coverage.reconciliation_status}.`,
  ];
  for (const line of metaLines) {
    const wrapped = doc.splitTextToSize(line, 612 - margin * 2) as string[];
    doc.text(wrapped, margin, y);
    y += 11 * wrapped.length;
  }
  if (ds.coverage.warnings.length) {
    doc.setTextColor(160, 20, 20);
    for (const w of ds.coverage.warnings.slice(0, 10)) {
      const wrapped = doc.splitTextToSize(`Warning: ${w}`, 612 - margin * 2) as string[];
      doc.text(wrapped, margin, y);
      y += 11 * wrapped.length;
    }
  }
  doc.setTextColor(0);
  y += 6;

  autoTable(doc, {
    startY: y,
    head: [['Currency', 'Credits', 'Debits', 'Net activity', 'Posted rows']],
    body: ds.totals.length
      ? ds.totals.map((t) => [t.currency, money(t.credits, t.currency), money(t.debits, t.currency), money(t.net, t.currency), String(t.rows)])
      : [['—', '0', '0', '0', '0']],
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [235, 235, 235], textColor: 20 },
    columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right' } },
    margin: { left: margin, right: margin },
  });

  const afterTotals = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 14;
  autoTable(doc, {
    startY: afterTotals,
    head: [['Account', 'Cur.', 'Opening', 'Credits', 'Debits', 'Net', 'Closing', 'Current (as of)', 'Coverage']],
    body: ds.accounts.map((a) => {
      const t = ds.accountTotals.find((x) => x.accountId === a.id);
      const cov = ds.coverage.accounts.find((c) => c.accountId === a.id);
      return [
        `${a.name}\n${a.orgName ?? ''} · ${a.kind}`,
        a.currency,
        a.openingBalance === null ? 'unavailable' : money(a.openingBalance, a.currency),
        t ? money(t.credits, a.currency) : '0',
        t ? money(t.debits, a.currency) : '0',
        t ? money(t.net, a.currency) : '0',
        a.closingBalance === null ? 'unavailable' : money(a.closingBalance, a.currency),
        a.currentBalance === null ? '—' : `${money(a.currentBalance, a.currency)}\n${(a.currentBalanceAsOf ?? 'unknown').slice(0, 16)}`,
        cov?.coverage ?? 'unknown',
      ];
    }),
    styles: { fontSize: 7, cellPadding: 2 },
    headStyles: { fillColor: [235, 235, 235], textColor: 20 },
    columnStyles: { 2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' }, 6: { halign: 'right' }, 7: { halign: 'right' } },
    margin: { left: margin, right: margin },
  });

  const ledger = (title: string, rows: ReportRow[]) => {
    const limit = pdfMaxRows();
    const shown = rows.slice(0, limit);
    const startY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 14;
    autoTable(doc, {
      startY,
      head: [[{ content: `${title} (${rows.length}${rows.length > limit ? `; first ${limit} shown, all rows in CSV/JSON` : ''})`, colSpan: 6, styles: { halign: 'left', fillColor: [245, 245, 245] } }], ['Date', 'Account', 'Description', 'Category', 'Cur.', 'Amount']],
      body: shown.length
        ? shown.map((r) => {
            const a = accountById.get(r.accountId);
            const currency = a?.currency ?? '';
            return [
              dateOnly(r.posted ?? r.transactedAt, tz),
              a?.name ?? '',
              [r.description, r.payee].filter(Boolean).join(' · '),
              r.category ?? '',
              currency,
              money(r.amount, currency),
            ];
          })
        : [['', '', 'None', '', '', '']],
      styles: { fontSize: 7, cellPadding: 2, overflow: 'linebreak' },
      headStyles: { fillColor: [235, 235, 235], textColor: 20 },
      columnStyles: { 0: { cellWidth: 60 }, 1: { cellWidth: 90 }, 4: { cellWidth: 32 }, 5: { halign: 'right', cellWidth: 70 } },
      margin: { left: margin, right: margin },
      showHead: 'everyPage',
    });
  };
  ledger('Posted ledger', ds.posted);
  if (ds.report.includePending) ledger('Pending appendix (not included in totals)', ds.pending);

  const notesY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 14;
  autoTable(doc, {
    startY: notesY,
    head: [['Notes']],
    body: ds.disclaimers.map((d) => [d]),
    styles: { fontSize: 7, cellPadding: 2 },
    headStyles: { fillColor: [235, 235, 235], textColor: 20 },
    margin: { left: margin, right: margin },
  });

  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i += 1) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(120);
    doc.text(`${GENERATED_BY_NOTICE}  Page ${i} of ${pages}`, margin, 792 - 20);
  }

  return Buffer.from(doc.output('arraybuffer'));
}
