'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

/**
 * Reports and Statements for /finances.
 *
 * Two things that must never be confused, kept in two sections with two
 * labels: a **Monthly/Quarterly activity report** is generated by CoinPay
 * from imported rows; an **Imported bank statement — user supplied** is a
 * PDF the merchant uploaded. Neither is called official, verified, or
 * complete anywhere on this screen.
 *
 * Viewing, refreshing or downloading here never calls the bank provider.
 * Only "Fetch missing activity" (a backfill job) spends request budget, and
 * it says how many requests it plans before it is queued.
 */

interface AccountLite {
  id: string;
  name: string;
  org_name: string | null;
  currency: string;
  effective_scope?: string;
  is_hidden?: boolean;
}

interface Report {
  id: string;
  revision: number;
  status: string;
  period: { selector: string; label: string; timezone: string; periodToDate: boolean; start: string; effectiveEnd: string };
  scope: string;
  accountIds: string[];
  provider_coverage: string | null;
  local_export_complete: boolean | null;
  reconciliation_status: string;
  rowCount: number | null;
  pendingCount: number | null;
  totals: Array<{ currency: string; credits: string; debits: string; net: string; rows: number }> | null;
  warnings: string[];
  errorMessage: string | null;
  artifacts: Array<{ format: string; bytes: number }>;
  createdAt: string;
  notice: string;
}

interface Statement {
  id: string;
  accountId: string;
  institutionLabel: string | null;
  label: string;
  periodStart: string;
  periodEnd: string;
  timezone: string;
  bytes: number;
  originalFilename: string | null;
  reconciliation: { state: string; difference: string; currency: string } | null;
  createdAt: string;
}

interface Job {
  id: string;
  kind: string;
  status: string;
  params: Record<string, unknown>;
  progress: Record<string, unknown>;
  nextAttemptAt: string | null;
  errorMessage: string | null;
}

interface ConnectionLite {
  id: string;
  provider: string;
  label: string | null;
  lifecycle_state?: string;
  sync_consent_at?: string | null;
  next_sync_at?: string | null;
  last_synced_at?: string | null;
}

interface Props {
  accounts: AccountLite[];
  connections?: ConnectionLite[];
  authHeaders: (extra?: HeadersInit) => HeadersInit;
  onNotice: (message: string | null) => void;
  onError: (message: string | null) => void;
  /** Which section to scroll to when mounted from a subroute. */
  focus?: 'reports' | 'statements' | null;
  /** Called after a change the parent should reload connections for. */
  onConnectionsChanged?: () => void;
}

type PeriodMode = 'month' | 'quarter' | 'custom';

const GUESSED_TZ = typeof Intl !== 'undefined' ? Intl.DateTimeFormat().resolvedOptions().timeZone : 'UTC';

function readError(data: unknown, fallback: string): string {
  const err = (data as { error?: unknown } | null)?.error;
  if (typeof err === 'string') return err;
  if (err && typeof err === 'object' && typeof (err as { message?: unknown }).message === 'string') return (err as { message: string }).message;
  return fallback;
}

function coverageLabel(value: string | null): string {
  if (value === 'available_window_fetched') return 'Provider history fetched (not independently verified)';
  if (value === 'partial') return 'History may be incomplete';
  return 'History may be incomplete (provider coverage unknown)';
}

function coverageTone(value: string | null): string {
  return value === 'available_window_fetched' ? 'text-emerald-300 border-emerald-500/30' : 'text-amber-300 border-amber-500/30';
}

function lastMonthSelector(): string {
  const d = new Date();
  d.setUTCDate(1);
  d.setUTCMonth(d.getUTCMonth() - 1);
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}`;
}

function lastQuarterSelector(): string {
  const d = new Date();
  const q = Math.floor(d.getUTCMonth() / 3); // current quarter 0..3
  const year = q === 0 ? d.getUTCFullYear() - 1 : d.getUTCFullYear();
  const prev = q === 0 ? 4 : q;
  return `${year}-Q${prev}`;
}

export default function ReportsAndStatements({ accounts, connections = [], authHeaders, onNotice, onError, focus = null, onConnectionsChanged }: Props) {
  const reportsRef = useRef<HTMLElement | null>(null);
  const statementsRef = useRef<HTMLElement | null>(null);
  const [consentBusy, setConsentBusy] = useState<string | null>(null);

  const toggleConsent = async (c: ConnectionLite) => {
    const next = !c.sync_consent_at;
    setConsentBusy(c.id);
    onError(null);
    try {
      const res = await fetch(`/api/finances/connections/${c.id}/consent`, {
        method: 'POST',
        headers: authHeaders({ 'Content-Type': 'application/json' }),
        body: JSON.stringify({ dailySync: next }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(readError(data, 'Could not update background sync'));
      onNotice(
        next
          ? 'Background sync on. The daemon pulls this connection every 30 minutes, within the provider request budget; the first pull starts now.'
          : 'Background sync off for this connection.',
      );
      onConnectionsChanged?.();
    } catch (err) {
      onError(err instanceof Error ? err.message : 'Could not update background sync');
    } finally {
      setConsentBusy(null);
    }
  };

  // ---- report builder -----------------------------------------------------
  const [mode, setMode] = useState<PeriodMode>('month');
  const [month, setMonth] = useState(lastMonthSelector());
  const [quarter, setQuarter] = useState(lastQuarterSelector());
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [timezone, setTimezone] = useState(GUESSED_TZ);
  const [scope, setScope] = useState<'all' | 'business' | 'personal'>('all');
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [strict, setStrict] = useState(false);
  const [estimateGaps, setEstimateGaps] = useState(false);
  const [coverage, setCoverage] = useState<{ provider_coverage: string; accounts: Array<{ accountId: string; name: string | null; coverage: string; fraction: number; capped: boolean }> } | null>(null);
  const [coverageLoading, setCoverageLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [backfilling, setBackfilling] = useState(false);
  const [jobs, setJobs] = useState<Job[]>([]);

  const [reports, setReports] = useState<Report[]>([]);
  const [reportsLoading, setReportsLoading] = useState(false);
  const [emailFor, setEmailFor] = useState<string | null>(null);
  const [emailTo, setEmailTo] = useState('');
  const [emailMessage, setEmailMessage] = useState('');
  const [emailFormats, setEmailFormats] = useState<string[]>(['pdf', 'csv']);
  const [emailing, setEmailing] = useState(false);

  const sendReportEmail = async (report: Report) => {
    setEmailing(true);
    onError(null);
    try {
      const res = await fetch(`/api/finances/reports/${report.id}/send`, {
        method: 'POST',
        headers: authHeaders({ 'Content-Type': 'application/json' }),
        body: JSON.stringify({ to: emailTo, formats: emailFormats, message: emailMessage || null }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(readError(data, 'Could not send the report'));
      onNotice(`Sent ${report.period.label} to ${data.sent.join(', ')}${data.failed?.length ? ` (failed: ${data.failed.map((f: { to: string }) => f.to).join(', ')})` : ''}. Download link expires ${String(data.linkExpiresAt).slice(0, 10)}.`);
      setEmailFor(null);
      setEmailMessage('');
    } catch (err) {
      onError(err instanceof Error ? err.message : 'Could not send the report');
    } finally {
      setEmailing(false);
    }
  };

  // ---- statements -----------------------------------------------------------
  const [statements, setStatements] = useState<Statement[]>([]);
  const [uploadAccount, setUploadAccount] = useState('');
  const [uploadPeriodMode, setUploadPeriodMode] = useState<PeriodMode>('month');
  const [uploadMonth, setUploadMonth] = useState(lastMonthSelector());
  const [uploadQuarter, setUploadQuarter] = useState(lastQuarterSelector());
  const [uploadFrom, setUploadFrom] = useState('');
  const [uploadTo, setUploadTo] = useState('');
  const [uploadLabel, setUploadLabel] = useState('');
  const [uploadFile, setUploadFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [reconcileFor, setReconcileFor] = useState<Statement | null>(null);
  const [recOpening, setRecOpening] = useState('');
  const [recClosing, setRecClosing] = useState('');
  const [recLiability, setRecLiability] = useState(false);
  const [recAck, setRecAck] = useState(false);
  const [recReport, setRecReport] = useState('');
  const [reconciling, setReconciling] = useState(false);

  const periodQuery = useMemo(() => {
    if (mode === 'month') return { period: month };
    if (mode === 'quarter') return { period: quarter };
    return { from, to };
  }, [mode, month, quarter, from, to]);

  const selectableAccounts = useMemo(
    () => accounts.filter((a) => scope === 'all' || a.effective_scope === scope),
    [accounts, scope],
  );

  useEffect(() => {
    // Default to every visible account in scope; the frozen list is what the
    // server records, so an empty selection is refused rather than guessed.
    setSelected(new Set(selectableAccounts.map((a) => a.id)));
  }, [selectableAccounts]);

  const loadReports = useCallback(async () => {
    setReportsLoading(true);
    try {
      const res = await fetch('/api/finances/reports?limit=25', { headers: authHeaders(), cache: 'no-store' });
      const data = await res.json();
      if (res.ok) setReports(data.reports ?? []);
    } catch {
      // Leave the list as it was; the page above still works.
    } finally {
      setReportsLoading(false);
    }
  }, [authHeaders]);

  const loadStatements = useCallback(async () => {
    try {
      const res = await fetch('/api/finances/statements?limit=100', { headers: authHeaders(), cache: 'no-store' });
      const data = await res.json();
      if (res.ok) setStatements(data.statements ?? []);
    } catch {
      // ignore
    }
  }, [authHeaders]);

  const loadJobs = useCallback(async () => {
    try {
      const res = await fetch('/api/finances/jobs?limit=10', { headers: authHeaders(), cache: 'no-store' });
      const data = await res.json();
      if (res.ok) setJobs((data.jobs ?? []).filter((j: Job) => ['queued', 'running', 'waiting_for_budget'].includes(j.status)));
    } catch {
      // ignore
    }
  }, [authHeaders]);

  useEffect(() => {
    void loadReports();
    void loadStatements();
    void loadJobs();
  }, [loadReports, loadStatements, loadJobs]);

  // Poll while anything is in flight. Polling reads our own tables only.
  const inFlight = reports.some((r) => r.status === 'queued' || r.status === 'generating') || jobs.length > 0;
  useEffect(() => {
    if (!inFlight) return;
    const timer = setInterval(() => {
      void loadReports();
      void loadJobs();
    }, 4000);
    return () => clearInterval(timer);
  }, [inFlight, loadReports, loadJobs]);

  useEffect(() => {
    const target = focus === 'reports' ? reportsRef.current : focus === 'statements' ? statementsRef.current : null;
    if (target) target.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }, [focus]);

  const checkCoverage = async () => {
    setCoverageLoading(true);
    setCoverage(null);
    try {
      const params = new URLSearchParams({ timezone });
      for (const [k, v] of Object.entries(periodQuery)) if (v) params.set(k, v);
      for (const id of selected) params.append('account', id);
      const res = await fetch(`/api/finances/coverage?${params.toString()}`, { headers: authHeaders(), cache: 'no-store' });
      const data = await res.json();
      if (!res.ok) throw new Error(readError(data, 'Could not check coverage'));
      setCoverage(data);
    } catch (err) {
      onError(err instanceof Error ? err.message : 'Could not check coverage');
    } finally {
      setCoverageLoading(false);
    }
  };

  const generate = async () => {
    if (selected.size === 0) {
      onError('Select at least one account for the report.');
      return;
    }
    setGenerating(true);
    onError(null);
    try {
      const res = await fetch('/api/finances/reports', {
        method: 'POST',
        headers: authHeaders({ 'Content-Type': 'application/json' }),
        body: JSON.stringify({ ...periodQuery, timezone, accountIds: [...selected], scope, strict, estimateGaps, formats: ['pdf', 'csv', 'json', 'html'] }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(readError(data, 'Could not queue the report'));
      onNotice(`Report queued for ${data.report.period.label}. It will appear below when ready; nothing was requested from the bank.`);
      await loadReports();
    } catch (err) {
      onError(err instanceof Error ? err.message : 'Could not queue the report');
    } finally {
      setGenerating(false);
    }
  };

  const backfill = async () => {
    setBackfilling(true);
    onError(null);
    try {
      const res = await fetch('/api/finances/sync-jobs', {
        method: 'POST',
        headers: authHeaders({ 'Content-Type': 'application/json' }),
        body: JSON.stringify({ kind: 'backfill', ...periodQuery, timezone }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(readError(data, 'Could not queue the fetch'));
      const planned = (data.jobs ?? []).reduce((n: number, j: Job) => n + Number(j.params.requestsPlanned ?? 0), 0);
      onNotice(`Fetch queued: ${data.jobs?.length ?? 1} job(s), ${planned} provider request(s) planned. It runs in the background and pauses if the daily budget runs out.`);
      await loadJobs();
    } catch (err) {
      onError(err instanceof Error ? err.message : 'Could not queue the fetch');
    } finally {
      setBackfilling(false);
    }
  };

  const download = async (url: string, fallbackName: string) => {
    try {
      const res = await fetch(url, { headers: authHeaders(), cache: 'no-store' });
      if (!res.ok) {
        let data: unknown = null;
        try { data = await res.json(); } catch { /* not JSON */ }
        throw new Error(readError(data, `Download failed (HTTP ${res.status})`));
      }
      const blob = await res.blob();
      const disposition = res.headers.get('content-disposition') ?? '';
      const match = /filename="?([^";]+)"?/i.exec(disposition);
      const objectUrl = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = objectUrl;
      a.download = match ? match[1] : fallbackName;
      a.style.visibility = 'hidden';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(objectUrl);
    } catch (err) {
      onError(err instanceof Error ? err.message : 'Download failed');
    }
  };

  const deleteReport = async (report: Report) => {
    if (!window.confirm(`Delete report ${report.period.label} (revision ${report.revision})? Its files and dataset are removed. Bank activity is not.`)) return;
    const res = await fetch(`/api/finances/reports/${report.id}`, { method: 'DELETE', headers: authHeaders() });
    if (!res.ok) onError(readError(await res.json().catch(() => null), 'Could not delete the report'));
    await loadReports();
  };

  const upload = async () => {
    if (!uploadFile || !uploadAccount) {
      onError('Choose a PDF and the account it belongs to.');
      return;
    }
    setUploading(true);
    onError(null);
    try {
      const form = new FormData();
      form.append('file', uploadFile, uploadFile.name);
      form.append('accountId', uploadAccount);
      form.append('timezone', timezone);
      if (uploadPeriodMode === 'month') form.append('period', uploadMonth);
      else if (uploadPeriodMode === 'quarter') form.append('period', uploadQuarter);
      else {
        form.append('from', uploadFrom);
        form.append('to', uploadTo);
      }
      if (uploadLabel.trim()) form.append('institutionLabel', uploadLabel.trim());
      const res = await fetch('/api/finances/statements', { method: 'POST', headers: authHeaders(), body: form });
      const data = await res.json();
      if (!res.ok) throw new Error(readError(data, 'Could not import the statement'));
      onNotice(data.duplicateOf === data.statement.id ? 'That statement was already imported.' : `Imported. ${data.note}`);
      setUploadFile(null);
      await loadStatements();
    } catch (err) {
      onError(err instanceof Error ? err.message : 'Could not import the statement');
    } finally {
      setUploading(false);
    }
  };

  const deleteStatement = async (s: Statement) => {
    if (!window.confirm(`Delete this imported statement (${s.periodStart} to ${s.periodEnd})? The document is removed; bank activity is not. Reconciliation evidence built on it becomes unavailable.`)) return;
    const res = await fetch(`/api/finances/statements/${s.id}`, { method: 'DELETE', headers: authHeaders() });
    if (!res.ok) onError(readError(await res.json().catch(() => null), 'Could not delete the statement'));
    await loadStatements();
  };

  const compatibleReports = (s: Statement | null): Report[] =>
    s
      ? reports.filter((r) => (r.status === 'ready' || r.status === 'superseded') && r.accountIds.includes(s.accountId))
      : [];

  const reconcile = async () => {
    if (!reconcileFor || !recReport) return;
    const account = accounts.find((a) => a.id === reconcileFor.accountId);
    setReconciling(true);
    onError(null);
    try {
      const res = await fetch(`/api/finances/statements/${reconcileFor.id}/reconciliations`, {
        method: 'POST',
        headers: authHeaders({ 'Content-Type': 'application/json' }),
        body: JSON.stringify({
          reportId: recReport,
          opening: recOpening.trim(),
          closing: recClosing.trim(),
          currency: account?.currency ?? 'USD',
          signConvention: recLiability ? 'liability_positive' : 'as_stated',
          acknowledge: recAck,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(readError(data, 'Could not reconcile'));
      const r = data.reconciliation;
      onNotice(`${r.state === 'mismatch' ? 'Mismatch' : r.state === 'user_reconciled' ? 'Reconciled by you' : 'Matched'}: expected closing ${r.expectedClosing}, entered ${r.normalized.closing}, difference ${r.difference} ${r.currency}. This is not bank verification.`);
      setReconcileFor(null);
      await loadStatements();
      await loadReports();
    } catch (err) {
      onError(err instanceof Error ? err.message : 'Could not reconcile');
    } finally {
      setReconciling(false);
    }
  };

  const accountName = (id: string) => {
    const a = accounts.find((x) => x.id === id);
    return a ? `${a.name}${a.org_name ? ` · ${a.org_name}` : ''}` : 'Account';
  };

  const inputClass = 'rounded border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-gray-200';
  const btnPrimary = 'rounded bg-purple-600 px-4 py-2 text-sm font-medium text-white hover:bg-purple-500 disabled:opacity-50';
  const btnSecondary = 'rounded border border-slate-600 px-3 py-2 text-sm text-gray-300 hover:bg-slate-800 disabled:opacity-50';

  return (
    <>
      {/* reports */}
      <section ref={reportsRef} id="reports" className="mb-8 rounded-lg border border-slate-700 bg-slate-900/50 p-6 scroll-mt-24">
        <div className="flex flex-wrap items-start justify-between gap-3 mb-1">
          <div>
            <h2 className="text-lg font-semibold text-white">Reports</h2>
            <p className="text-xs text-gray-500">
              Monthly and quarterly activity reports, generated by CoinPay from imported account data. Not institution-issued statements.
            </p>
          </div>
        </div>

        {connections.filter((c) => c.lifecycle_state !== 'disconnected').length > 0 && (
          <div className="mt-3 rounded border border-slate-800 bg-slate-950/40 p-3">
            <div className="text-xs text-gray-400 mb-1">
              Background sync. The daemon pulls opted-in connections every 30 minutes, throttled to the provider request budget (20 a day per connection, 4 kept for Sync now).
            </div>
            <div className="flex flex-wrap gap-2">
              {connections
                .filter((c) => c.lifecycle_state !== 'disconnected')
                .map((c) => (
                  <label key={c.id} className="flex items-center gap-2 rounded border border-slate-700 px-2 py-1 text-xs text-gray-200">
                    <input
                      type="checkbox"
                      checked={Boolean(c.sync_consent_at)}
                      disabled={consentBusy === c.id}
                      onChange={() => toggleConsent(c)}
                    />
                    {c.label || c.provider}
                    <span className="text-gray-500">
                      {c.sync_consent_at
                        ? `next ${c.next_sync_at ? new Date(c.next_sync_at).toLocaleTimeString() : 'soon'}`
                        : 'off'}
                    </span>
                  </label>
                ))}
            </div>
          </div>
        )}

        <div className="grid gap-3 md:grid-cols-4 mt-4">
          <label className="text-xs text-gray-400">
            Period
            <div className="flex gap-1 mt-1">
              {(['month', 'quarter', 'custom'] as PeriodMode[]).map((m) => (
                <button key={m} type="button" onClick={() => setMode(m)} className={`rounded px-2 py-1 text-xs ${mode === m ? 'bg-purple-600 text-white' : 'border border-slate-700 text-gray-300'}`}>
                  {m === 'month' ? 'Month' : m === 'quarter' ? 'Quarter' : 'Custom'}
                </button>
              ))}
            </div>
            {mode === 'month' && <input type="month" value={month} onChange={(e) => setMonth(e.target.value)} className={`${inputClass} mt-1 w-full`} />}
            {mode === 'quarter' && <input type="text" value={quarter} onChange={(e) => setQuarter(e.target.value.toUpperCase())} placeholder="2026-Q2" className={`${inputClass} mt-1 w-full`} />}
            {mode === 'custom' && (
              <div className="flex gap-1 mt-1">
                <input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className={`${inputClass} w-full`} aria-label="From (inclusive)" />
                <input type="date" value={to} onChange={(e) => setTo(e.target.value)} className={`${inputClass} w-full`} aria-label="To (exclusive)" />
              </div>
            )}
            {mode === 'custom' && <span className="text-[10px] text-gray-500">The end date is exclusive.</span>}
          </label>
          <label className="text-xs text-gray-400">
            Timezone
            <input type="text" value={timezone} onChange={(e) => setTimezone(e.target.value)} className={`${inputClass} mt-1 w-full`} placeholder="America/Los_Angeles" />
            <span className="text-[10px] text-gray-500">Calendar months are measured in this zone.</span>
          </label>
          <label className="text-xs text-gray-400">
            Scope
            <select value={scope} onChange={(e) => setScope(e.target.value as 'all' | 'business' | 'personal')} className={`${inputClass} mt-1 w-full`}>
              <option value="all">All accounts</option>
              <option value="business">Business</option>
              <option value="personal">Personal</option>
            </select>
          </label>
          <div className="text-xs text-gray-400 flex flex-col gap-1 pb-2 justify-end">
            <label className="flex items-center gap-2">
              <input type="checkbox" checked={strict} onChange={(e) => setStrict(e.target.checked)} />
              Strict: refuse unless provider history was fetched for the whole period
            </label>
            <label className="flex items-center gap-2" title="Fills the days before the first transaction the bank supplied with an extrapolation of the observed daily average. Shown in its own section, labelled as an estimate, never mixed into observed totals.">
              <input type="checkbox" checked={estimateGaps} onChange={(e) => setEstimateGaps(e.target.checked)} />
              Estimate the start of the period the bank did not supply (labelled as estimate)
            </label>
          </div>
        </div>

        <div className="mt-3 text-xs text-gray-400">Accounts ({selected.size} selected)</div>
        <div className="mt-1 flex flex-wrap gap-2">
          {selectableAccounts.map((a) => (
            <label key={a.id} className={`rounded border px-2 py-1 text-xs cursor-pointer ${selected.has(a.id) ? 'border-purple-500 text-gray-100' : 'border-slate-700 text-gray-500'}`}>
              <input
                type="checkbox"
                className="mr-1"
                checked={selected.has(a.id)}
                onChange={(e) => {
                  const next = new Set(selected);
                  if (e.target.checked) next.add(a.id);
                  else next.delete(a.id);
                  setSelected(next);
                }}
              />
              {a.name} <span className="text-gray-500">{a.currency}</span>
            </label>
          ))}
          {selectableAccounts.length === 0 && <span className="text-xs text-gray-500">No accounts in this scope.</span>}
        </div>

        {coverage && (
          <div className={`mt-3 rounded border px-3 py-2 text-xs ${coverageTone(coverage.provider_coverage)}`}>
            {coverageLabel(coverage.provider_coverage)}
            <ul className="mt-1 text-gray-400">
              {coverage.accounts.map((c) => (
                <li key={c.accountId}>
                  {c.name ?? c.accountId}: {c.coverage.replace(/_/g, ' ')} ({Math.round(c.fraction * 100)}%){c.capped ? ' · a fetch was cut short' : ''}
                </li>
              ))}
            </ul>
          </div>
        )}

        <div className="mt-4 flex flex-wrap gap-2">
          <button type="button" onClick={generate} disabled={generating} className={btnPrimary}>
            {generating ? 'Queuing…' : 'Generate report'}
          </button>
          <button type="button" onClick={checkCoverage} disabled={coverageLoading} className={btnSecondary}>
            {coverageLoading ? 'Checking…' : 'Check coverage'}
          </button>
          <button type="button" onClick={backfill} disabled={backfilling} className={btnSecondary} title="Spends provider request budget">
            {backfilling ? 'Queuing…' : 'Fetch missing/older activity'}
          </button>
        </div>

        {jobs.length > 0 && (
          <ul className="mt-3 text-xs text-gray-400">
            {jobs.map((j) => (
              <li key={j.id}>
                {j.kind} · {j.status.replace(/_/g, ' ')}
                {Array.isArray(j.progress.windowsDone) && j.params.requestsPlanned ? ` · ${(j.progress.windowsDone as unknown[]).length}/${String(j.params.requestsPlanned)} chunks` : ''}
                {j.nextAttemptAt ? ` · next attempt ${new Date(j.nextAttemptAt).toLocaleString()}` : ''}
                {j.errorMessage ? ` · ${j.errorMessage}` : ''}
              </li>
            ))}
          </ul>
        )}

        <div className="mt-6">
          <h3 className="text-sm font-semibold text-gray-200 mb-2">Report history {reportsLoading && <span className="text-gray-500 font-normal">· refreshing</span>}</h3>
          {reports.length === 0 && <p className="text-xs text-gray-500">No reports yet.</p>}
          <div className="space-y-2">
            {reports.map((r) => (
              <div key={r.id} className="rounded border border-slate-800 bg-slate-950/40 p-3">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div>
                    <span className="text-sm text-gray-100">
                      {r.period.label} <span className="text-gray-500">· rev {r.revision} · {r.scope} · {r.accountIds.length} account(s)</span>
                    </span>
                    <div className="text-xs text-gray-500">
                      {new Date(r.createdAt).toLocaleString()} · {r.period.timezone}
                    </div>
                  </div>
                  <div className="flex flex-wrap gap-1 items-center">
                    <span className={`rounded border px-2 py-0.5 text-xs ${r.status === 'ready' ? 'border-emerald-500/30 text-emerald-300' : r.status === 'failed' ? 'border-red-500/30 text-red-300' : 'border-slate-600 text-gray-300'}`}>
                      {r.status}
                    </span>
                    {r.period.periodToDate && <span className="rounded border border-slate-600 px-2 py-0.5 text-xs text-gray-300">Period to date</span>}
                    {r.status === 'ready' && (
                      <span className={`rounded border px-2 py-0.5 text-xs ${coverageTone(r.provider_coverage)}`}>{coverageLabel(r.provider_coverage)}</span>
                    )}
                    {r.reconciliation_status !== 'not_attempted' && (
                      <span className="rounded border border-slate-600 px-2 py-0.5 text-xs text-gray-300">reconciliation: {r.reconciliation_status.replace(/_/g, ' ')}</span>
                    )}
                  </div>
                </div>
                {r.status === 'ready' && r.totals && (
                  <div className="mt-2 text-xs text-gray-400">
                    {r.totals.map((t) => (
                      <span key={t.currency} className="mr-4">
                        {t.currency}: credits {t.credits} · debits {t.debits} · net {t.net} · {t.rows} rows
                      </span>
                    ))}
                    {r.pendingCount ? <span>· {r.pendingCount} pending (excluded)</span> : null}
                  </div>
                )}
                {r.warnings.length > 0 && (
                  <ul className="mt-1 text-xs text-amber-300">
                    {r.warnings.slice(0, 5).map((w, i) => (
                      <li key={i}>{w}</li>
                    ))}
                  </ul>
                )}
                {r.errorMessage && <div className="mt-1 text-xs text-red-300">{r.errorMessage}</div>}
                <div className="mt-2 flex flex-wrap gap-2">
                  {(r.status === 'ready' || r.status === 'superseded') &&
                    ['pdf', 'csv', 'json', 'html'].map((f) => (
                      <button key={f} type="button" className={btnSecondary} onClick={() => download(`/api/finances/reports/${r.id}/download?format=${f}`, `report-${r.period.selector}.${f}`)}>
                        {f.toUpperCase()}
                      </button>
                    ))}
                  {(r.status === 'ready' || r.status === 'superseded') && (
                    <button type="button" className={btnSecondary} onClick={() => { setEmailFor(emailFor === r.id ? null : r.id); }}>
                      Email
                    </button>
                  )}
                  {r.status !== 'deleted' && (
                    <button type="button" className="rounded border border-red-500/30 px-3 py-2 text-xs text-red-300 hover:bg-red-500/10" onClick={() => deleteReport(r)}>
                      Delete
                    </button>
                  )}
                </div>
                {emailFor === r.id && (
                  <div className="mt-3 rounded border border-slate-700 p-3">
                    <div className="text-xs text-gray-400 mb-2">
                      Email this report. Recipients get the files attached and a download link that needs no login and expires in 14 days. Bank data leaves CoinPay when you press send.
                    </div>
                    <div className="grid gap-2 md:grid-cols-3">
                      <input type="text" value={emailTo} onChange={(e) => setEmailTo(e.target.value)} placeholder="cpa@example.com, you@example.com" className={inputClass} />
                      <input type="text" value={emailMessage} onChange={(e) => setEmailMessage(e.target.value)} placeholder="Optional note" className={inputClass} />
                      <div className="flex items-center gap-2 text-xs text-gray-400">
                        {['pdf', 'csv', 'json', 'html'].map((f) => (
                          <label key={f}><input type="checkbox" className="mr-1" checked={emailFormats.includes(f)} onChange={(e) => setEmailFormats(e.target.checked ? [...emailFormats, f] : emailFormats.filter((x) => x !== f))} />{f.toUpperCase()}</label>
                        ))}
                      </div>
                    </div>
                    <button type="button" onClick={() => sendReportEmail(r)} disabled={emailing || !emailTo.trim() || emailFormats.length === 0} className={`${btnPrimary} mt-2`}>
                      {emailing ? 'Sending…' : 'Send'}
                    </button>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* statements */}
      <section ref={statementsRef} id="statements" className="mb-8 rounded-lg border border-slate-700 bg-slate-900/50 p-6 scroll-mt-24">
        <h2 className="text-lg font-semibold text-white">Statements</h2>
        <p className="text-xs text-gray-500">
          Original PDFs you supply, kept privately beside the account and period you say they cover. Nothing is read out of them, and CoinPay does not verify their issuer.
        </p>

        <div className="grid gap-3 md:grid-cols-4 mt-4">
          <label className="text-xs text-gray-400">
            Account
            <select value={uploadAccount} onChange={(e) => setUploadAccount(e.target.value)} className={`${inputClass} mt-1 w-full`}>
              <option value="">Choose…</option>
              {accounts.map((a) => (
                <option key={a.id} value={a.id}>
                  {a.name}{a.org_name ? ` · ${a.org_name}` : ''} ({a.currency})
                </option>
              ))}
            </select>
          </label>
          <label className="text-xs text-gray-400">
            Statement period
            <div className="flex gap-1 mt-1">
              {(['month', 'quarter', 'custom'] as PeriodMode[]).map((m) => (
                <button key={m} type="button" onClick={() => setUploadPeriodMode(m)} className={`rounded px-2 py-1 text-xs ${uploadPeriodMode === m ? 'bg-purple-600 text-white' : 'border border-slate-700 text-gray-300'}`}>
                  {m === 'month' ? 'Month' : m === 'quarter' ? 'Quarter' : 'Custom'}
                </button>
              ))}
            </div>
            {uploadPeriodMode === 'month' && <input type="month" value={uploadMonth} onChange={(e) => setUploadMonth(e.target.value)} className={`${inputClass} mt-1 w-full`} />}
            {uploadPeriodMode === 'quarter' && <input type="text" value={uploadQuarter} onChange={(e) => setUploadQuarter(e.target.value.toUpperCase())} className={`${inputClass} mt-1 w-full`} />}
            {uploadPeriodMode === 'custom' && (
              <div className="flex gap-1 mt-1">
                <input type="date" value={uploadFrom} onChange={(e) => setUploadFrom(e.target.value)} className={`${inputClass} w-full`} aria-label="Statement start" />
                <input type="date" value={uploadTo} onChange={(e) => setUploadTo(e.target.value)} className={`${inputClass} w-full`} aria-label="Statement end (exclusive)" />
              </div>
            )}
          </label>
          <label className="text-xs text-gray-400">
            Institution label
            <input type="text" value={uploadLabel} onChange={(e) => setUploadLabel(e.target.value)} className={`${inputClass} mt-1 w-full`} placeholder="As printed on the statement" />
          </label>
          <label className="text-xs text-gray-400">
            PDF (max 25 MiB, not password-protected)
            <input type="file" accept="application/pdf,.pdf" onChange={(e) => setUploadFile(e.target.files?.[0] ?? null)} className="mt-1 block w-full text-xs text-gray-300" />
          </label>
        </div>
        <div className="mt-3">
          <button type="button" onClick={upload} disabled={uploading || !uploadFile || !uploadAccount} className={btnPrimary}>
            {uploading ? 'Importing…' : 'Upload original PDF'}
          </button>
        </div>

        <div className="mt-6">
          <h3 className="text-sm font-semibold text-gray-200 mb-2">Library</h3>
          {statements.length === 0 && <p className="text-xs text-gray-500">No statements imported.</p>}
          <div className="space-y-2">
            {statements.map((s) => (
              <div key={s.id} className="rounded border border-slate-800 bg-slate-950/40 p-3">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div>
                    <div className="text-sm text-gray-100">
                      {s.institutionLabel || 'Imported bank statement'} <span className="text-gray-500">· user supplied</span>
                    </div>
                    <div className="text-xs text-gray-500">
                      {accountName(s.accountId)} · {s.periodStart} to {s.periodEnd} (exclusive) · {(s.bytes / 1024).toFixed(0)} KiB
                    </div>
                  </div>
                  <div className="flex flex-wrap gap-1 items-center">
                    <span className={`rounded border px-2 py-0.5 text-xs ${s.reconciliation?.state === 'user_reconciled' || s.reconciliation?.state === 'matched' ? 'border-emerald-500/30 text-emerald-300' : s.reconciliation?.state === 'mismatch' ? 'border-red-500/30 text-red-300' : 'border-amber-500/30 text-amber-300'}`}>
                      {s.reconciliation ? `${s.reconciliation.state.replace(/_/g, ' ')} (diff ${s.reconciliation.difference} ${s.reconciliation.currency})` : 'Imported PDF — not yet reconciled'}
                    </span>
                  </div>
                </div>
                <div className="mt-2 flex flex-wrap gap-2">
                  <button type="button" className={btnSecondary} onClick={() => download(`/api/finances/statements/${s.id}/download`, s.originalFilename ?? `statement-${s.periodStart}.pdf`)}>
                    Download original
                  </button>
                  <button
                    type="button"
                    className={btnSecondary}
                    onClick={() => {
                      setReconcileFor(reconcileFor?.id === s.id ? null : s);
                      setRecReport(compatibleReports(s)[0]?.id ?? '');
                      setRecOpening('');
                      setRecClosing('');
                      setRecAck(false);
                    }}
                  >
                    Reconcile
                  </button>
                  <button type="button" className="rounded border border-red-500/30 px-3 py-2 text-xs text-red-300 hover:bg-red-500/10" onClick={() => deleteStatement(s)}>
                    Delete
                  </button>
                </div>
                {reconcileFor?.id === s.id && (
                  <div className="mt-3 rounded border border-slate-700 p-3">
                    <div className="text-xs text-gray-400 mb-2">
                      Enter the balances printed on the statement, in {accounts.find((a) => a.id === s.accountId)?.currency ?? 'the account currency'}. Expected closing = opening + posted activity in the chosen report. A match plus your acknowledgement records “user reconciled”; it is not bank verification.
                    </div>
                    {compatibleReports(s).length === 0 ? (
                      <div className="text-xs text-amber-300">No ready report includes this account for this period yet. Generate a report for {s.periodStart} to {s.periodEnd} first.</div>
                    ) : (
                      <div className="grid gap-2 md:grid-cols-4">
                        <select value={recReport} onChange={(e) => setRecReport(e.target.value)} className={inputClass}>
                          {compatibleReports(s).map((r) => (
                            <option key={r.id} value={r.id}>
                              {r.period.label} rev {r.revision} ({r.status})
                            </option>
                          ))}
                        </select>
                        <input type="text" inputMode="decimal" placeholder="Opening balance" value={recOpening} onChange={(e) => setRecOpening(e.target.value)} className={inputClass} />
                        <input type="text" inputMode="decimal" placeholder="Closing balance" value={recClosing} onChange={(e) => setRecClosing(e.target.value)} className={inputClass} />
                        <div className="flex flex-col gap-1 text-xs text-gray-400">
                          <label><input type="checkbox" className="mr-1" checked={recLiability} onChange={(e) => setRecLiability(e.target.checked)} />Statement shows amounts owed as positive (credit card)</label>
                          <label><input type="checkbox" className="mr-1" checked={recAck} onChange={(e) => setRecAck(e.target.checked)} />I checked the statement against the report</label>
                        </div>
                        <button type="button" onClick={reconcile} disabled={reconciling || !recReport || !recOpening || !recClosing} className={`${btnPrimary} md:col-span-4 justify-self-start`}>
                          {reconciling ? 'Checking…' : 'Check balances'}
                        </button>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
