// Generated by CrawlProof Audience Hub — safe to edit.
// Sends trusted server-side events (user/customer lifecycle) to CrawlProof.
// Docs: https://crawlproof.com/docs/stats-tracker

import { createCrawlproofClient } from "@profullstack/stack/crawlproof";

const client = createCrawlproofClient({
  apiKey: process.env.CRAWLPROOF_PROJECT_KEY,
  baseUrl: process.env.CRAWLPROOF_INGEST_URL?.replace(/\/api\/events$/, ""),
  project: "coinpayportal.com",
});

export const sendCrawlProofEvent = (
  event: Parameters<typeof client.sendEvent>[0]
): Promise<void> => client.sendEvent(event).then(() => undefined);

// Example:
//   await sendCrawlProofEvent({
//     event: "user.created",
//     email: user.email,
//     name: user.name,
//     user_id: user.id,
//     marketing_consent: Boolean(user.marketingConsent),
//   });
