import { describe, it, expect, vi } from 'vitest';
import { mkdtempSync, readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { runFinancesCommand, writeDownload, CliExit, EXIT } from '../src/finances-commands.js';

/**
 * The extended `coinpay finances` contract, exercised against a fake client
 * so the exit codes, stdout/stderr split and file handling are pinned
 * without spawning the binary.
 */

function fakeClient(routes) {
  const calls = [];
  return {
    calls,
    async request(path, options = {}) {
      calls.push({ path, options });
      const handler = routes[`${options.method || 'GET'} ${path.split('?')[0]}`] || routes[`GET ${path}`];
      if (!handler) throw Object.assign(new Error(`no route ${options.method || 'GET'} ${path}`), { status: 404, response: { error: { code: 'not_found', message: 'Not found' } } });
      const result = await handler(path, options);
      if (result && result.__error) {
        const err = new Error(result.__error.message);
        err.status = result.__status || 400;
        err.response = { error: result.__error };
        throw err;
      }
      return result;
    },
    async requestBinary(path) {
      calls.push({ path, binary: true });
      const handler = routes[`BINARY ${path.split('?')[0]}`];
      if (!handler) throw Object.assign(new Error('no binary route'), { status: 404 });
      return handler(path);
    },
    async requestForm(path, form) {
      calls.push({ path, form: true });
      const handler = routes[`FORM ${path}`];
      return handler(path, form);
    },
  };
}

function ctxFor(client) {
  const out = [];
  const err = [];
  return { ctx: { client, out: (l) => out.push(l), err: (l) => err.push(l) }, out, err };
}

const READY_REPORT = {
  id: 'rep-1', revision: 1, status: 'ready', period: { selector: '2026-08', label: 'August 2026', timezone: 'UTC' },
  provider_coverage: 'available_window_fetched', local_export_complete: true, rowCount: 3, warnings: [], notice: 'Generated by CoinPay', errorCode: null,
};

describe('period flags', () => {
  it('rejects --period together with --from/--to, and bad dates, with exit 2', async () => {
    const { ctx, err } = ctxFor(fakeClient({}));
    expect(await runFinancesCommand('report', [], { period: '2026-08', from: '2026-01-01', to: '2026-02-01' }, ctx)).toBe(EXIT.INVALID);
    expect(err.join('\n')).toMatch(/not both/);
    expect(await runFinancesCommand('report', [], { from: '2026-02-30x', to: '2026-03-01' }, ctx)).toBe(EXIT.INVALID);
    expect(await runFinancesCommand('report', [], { period: 'august' }, ctx)).toBe(EXIT.INVALID);
    expect(await runFinancesCommand('report', [], { period: '2026-08', timezone: 'EST' }, ctx)).toBe(EXIT.INVALID);
    expect(await runFinancesCommand('report', [], {}, ctx)).toBe(EXIT.INVALID);
  });
});

describe('report', () => {
  it('queues without waiting and prints the job id, exit 0', async () => {
    const client = fakeClient({
      'POST /finances/reports': async () => ({ report: { ...READY_REPORT, status: 'queued' }, job: { id: 'job-1', status: 'queued' } }),
    });
    const { ctx, out, err } = ctxFor(client);
    const code = await runFinancesCommand('report', [], { period: '2026-08', json: true }, ctx);
    expect(code).toBe(EXIT.OK);
    // stdout is only the JSON result; progress went to stderr.
    const parsed = JSON.parse(out.join('\n'));
    expect(parsed.job.id).toBe('job-1');
    expect(err.join('\n')).toMatch(/Queued/);
    const body = JSON.parse(client.calls[0].options.body);
    expect(body.formats).toEqual(['pdf', 'json']);
    expect(body.strict).toBe(false);
  });

  it('waits, downloads and writes the file with owner-only permissions when --output is given', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'coinpay-report-'));
    const target = join(dir, 'aug.pdf');
    let polls = 0;
    const client = fakeClient({
      'POST /finances/reports': async () => ({ report: { ...READY_REPORT, status: 'queued' }, job: { id: 'job-1', status: 'queued' } }),
      'GET /finances/reports/rep-1': async () => {
        polls += 1;
        return { report: polls < 2 ? { ...READY_REPORT, status: 'generating' } : READY_REPORT, job: { id: 'job-1', status: polls < 2 ? 'running' : 'completed' } };
      },
      'BINARY /finances/reports/rep-1/download': async () => ({ bytes: new Uint8Array(Buffer.from('%PDF-1.4 test')), sha256: 'abc', contentType: 'application/pdf' }),
    });
    const { ctx, out } = ctxFor(client);
    const code = await runFinancesCommand('report', [], { period: '2026-08', output: target, format: 'pdf' }, ctx);
    expect(code).toBe(EXIT.OK);
    expect(readFileSync(target, 'utf8')).toBe('%PDF-1.4 test');
    if (process.platform !== 'win32') expect(statSync(target).mode & 0o777).toBe(0o600);
    expect(out.join('\n')).toMatch(/Wrote/);
    // A second run refuses to overwrite.
    const again = await runFinancesCommand('report', [], { period: '2026-08', output: target }, ctxFor(client).ctx);
    expect(again).toBe(EXIT.INVALID);
  });

  it('exits 3 under --strict when provider coverage is partial', async () => {
    const client = fakeClient({
      'POST /finances/reports': async () => ({ report: { ...READY_REPORT, status: 'queued' }, job: { id: 'job-1' } }),
      'GET /finances/reports/rep-1': async () => ({ report: { ...READY_REPORT, status: 'failed', errorCode: 'provider_coverage_partial', errorMessage: 'Strict mode: partial' }, job: { id: 'job-1', status: 'completed' } }),
    });
    const { ctx } = ctxFor(client);
    expect(await runFinancesCommand('report', [], { period: '2026-08', strict: true, wait: true }, ctx)).toBe(EXIT.STRICT);
  });

  it('never presents a report whose local export is incomplete as success', async () => {
    const client = fakeClient({
      'POST /finances/reports': async () => ({ report: { ...READY_REPORT, status: 'queued' }, job: { id: 'job-1' } }),
      'GET /finances/reports/rep-1': async () => ({ report: { ...READY_REPORT, local_export_complete: false }, job: null }),
    });
    const { ctx } = ctxFor(client);
    expect(await runFinancesCommand('report', [], { period: '2026-08', wait: true }, ctx)).toBe(EXIT.STRICT);
  });

  it('maps an auth failure to exit 4 and a provider failure to exit 5', async () => {
    const denied = fakeClient({ 'POST /finances/reports': async () => ({ __error: { code: 'unauthorized', message: 'Not authenticated' }, __status: 401 }) });
    expect(await runFinancesCommand('report', [], { period: '2026-08' }, ctxFor(denied).ctx)).toBe(EXIT.AUTH);
    const broken = fakeClient({ 'POST /finances/reports': async () => ({ __error: { code: 'provider_error', message: 'boom' }, __status: 502 }) });
    expect(await runFinancesCommand('report', [], { period: '2026-08' }, ctxFor(broken).ctx)).toBe(EXIT.FAILURE);
  });
});

describe('connect', () => {
  it('refuses a token on the command line', async () => {
    const { ctx, err } = ctxFor(fakeClient({}));
    expect(await runFinancesCommand('connect', [], { 'setup-token': 'abc' }, ctx)).toBe(EXIT.INVALID);
    expect(err.join('\n')).toMatch(/shell history/);
  });
});

describe('backfill and jobs', () => {
  it('reports the planned request count and the job state', async () => {
    const client = fakeClient({
      'POST /finances/sync-jobs': async () => ({ jobs: [{ id: 'job-9', kind: 'backfill', status: 'queued', params: { requestsPlanned: 3 }, progress: {} }] }),
    });
    const { ctx, out, err } = ctxFor(client);
    expect(await runFinancesCommand('backfill', [], { period: '2026-Q2', timezone: 'America/Los_Angeles', json: true }, ctx)).toBe(EXIT.OK);
    expect(err.join('\n')).toMatch(/3 provider request/);
    expect(JSON.parse(out.join('\n')).jobs[0].id).toBe('job-9');
    expect(JSON.parse(client.calls[0].options.body)).toMatchObject({ kind: 'backfill', period: '2026-Q2', timezone: 'America/Los_Angeles' });
  });

  it('reads a job without making a provider request', async () => {
    const client = fakeClient({ 'GET /finances/jobs/job-9': async () => ({ job: { id: 'job-9', kind: 'backfill', status: 'waiting_for_budget', params: { requestsPlanned: 3 }, progress: { windowsDone: [0] }, nextAttemptAt: '2026-09-13T00:00:00Z' } }) });
    const { ctx, out } = ctxFor(client);
    expect(await runFinancesCommand('jobs', ['get', 'job-9'], {}, ctx)).toBe(EXIT.OK);
    expect(out.join('\n')).toMatch(/1\/3 windows/);
    expect(client.calls).toHaveLength(1);
  });
});

describe('statements', () => {
  it('imports a PDF and says that no transactions were imported', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'coinpay-stmt-'));
    const pdf = join(dir, 'aug.pdf');
    writeFileSync(pdf, '%PDF-1.4\n1 0 obj\nendobj\ntrailer\nstartxref\n%%EOF');
    const client = fakeClient({
      'FORM /finances/statements': async (_path, form) => {
        expect(form.get('accountId')).toBe('acct-1');
        expect(form.get('period')).toBe('2026-08');
        expect(form.get('file')).toBeInstanceOf(Blob);
        return { statement: { id: 'st-1', periodStart: '2026-08-01', periodEnd: '2026-09-01' }, duplicateOf: null, note: 'No transactions were imported from it.' };
      },
    });
    const { ctx, out } = ctxFor(client);
    expect(await runFinancesCommand('statements', ['import', pdf], { account: 'acct-1', period: '2026-08' }, ctx)).toBe(EXIT.OK);
    expect(out.join('\n')).toMatch(/No transactions were imported/);
  });

  it('requires --yes to delete, and a mismatch reconciliation exits 3', async () => {
    const client = fakeClient({
      'POST /finances/statements/st-1/reconciliations': async () => ({ reconciliation: { state: 'mismatch', expectedClosing: '10', normalized: { closing: '12' }, difference: '2', currency: 'USD' } }),
    });
    const { ctx } = ctxFor(client);
    expect(await runFinancesCommand('statements', ['delete', 'st-1'], {}, ctx)).toBe(EXIT.INVALID);
    expect(await runFinancesCommand('statements', ['reconcile', 'st-1'], { report: 'rep-1', opening: '0', closing: '12', currency: 'USD' }, ctx)).toBe(EXIT.STRICT);
  });
});

describe('writeDownload', () => {
  it('is atomic and refuses to overwrite without the flag', () => {
    const dir = mkdtempSync(join(tmpdir(), 'coinpay-dl-'));
    const target = join(dir, 'out.csv');
    writeDownload(target, Buffer.from('a'));
    expect(() => writeDownload(target, Buffer.from('b'))).toThrow(CliExit);
    writeDownload(target, Buffer.from('b'), { overwrite: true });
    expect(readFileSync(target, 'utf8')).toBe('b');
    expect(existsSync(join(dir, 'out.csv.tmp'))).toBe(false);
  });
});

describe('unknown subcommand', () => {
  it('returns null so the binary can fall through to its own usage', async () => {
    expect(await runFinancesCommand('nope', [], {}, ctxFor(fakeClient({})).ctx)).toBeNull();
    vi.restoreAllMocks();
  });
});
